builtin_interfaces/Time stamp
uint64 definition_hash
# ==========================
# Bool types
# ==========================
string[] bool_names
# ==========================
# Integer types
# ==========================
string[] int8_names
string[] uint8_names
string[] int16_names
string[] uint16_names
string[] int32_names
string[] uint32_names
string[] int64_names
string[] uint64_names
# ==========================
# Floating point types
# ==========================
string[] float32_names
string[] float64_names