builtin_interfaces/Time stamp
uint64 definition_hash
# ==========================
# Bool types
# ==========================
bool[] bool_values
# ==========================
# Integer types
# ==========================
int8[] int8_values
uint8[] uint8_values
int16[] int16_values
uint16[] uint16_values
int32[] int32_values
uint32[] uint32_values
int64[] int64_values
uint64[] uint64_values
# ==========================
# Floating point types
# ==========================
float32[] float32_values
float64[] float64_values